### PR TITLE
Janette DOC-215

### PR DESCRIPTION
**Pull request by janettelynch**

### CODE REVIEW

**Comment by kyorkJ1** [comment]
I am good with the changes.

**Comment by janettelynch** [comment]
@kyorkJ1 Who is a codeowner approver?

**Comment by VDubber** [comment]
@janettelynch Please resolve conflicts with the specified files above.

**Comment by Gonzalo-Avalos-Ribas** [comment]
Hey team! We recently added a way to auto-document permissions in docs/jupiterone.md file.
This is why main has some changes in the .md that you didn't add.
I think the quickest fix is to merge locally main into your branch, resolve the conflict with your file (your docs/jupiterone.md with your changes) and then just commit again.
The action of commiting executes the pre-commit hook that attaches the documentation into the jupiterone.md.
Cheers!

**Comment by Gonzalo-Avalos-Ribas** [comment]
Other than this, i see we are updating the information for setting up an ingestion in Azure. We took the time to go over each step and review what particular permissions each needed, so that we don't have the necessity to ask the user to give the Reader Role to the application, this is way too permissive (about 6000 + permissions, when in our analysis ingestion needs about 200). I'm talking next steps, but we do have the list now!

**Comment by janettelynch** [comment]
@VDubber I have resolved the conflict.

**Review by Gonzalo-Avalos-Ribas — APPROVED** [review]
Looks Good To Me!
Mind if i ask why are we adding .png to the project?

**Comment by janettelynch** [comment]
@Gonzalo-Avalos-Ribas Images always speak better than words. Kristal provided these images to  help comprehension.

**Pull request merged**
