### PR TITLE
339 management groups

### PR DESCRIPTION
**Pull request by ndowmon**
This introduces a new config field `ingestManagementGroups` that should be used like the `ingestActiveDirectory` config field. However, it may be best to remove `intestManagementGroups` and just ingest them when `ingestActiveDirectory` is set to `true`.

Here's a look at the management group structure in Azure:
Screen Shot 2021-05-20 at 11 45 28 AM

Screen Shot 2021-05-20 at 11 44 52 AM

### CODE REVIEW

**Review by kenanwarren — DISMISSED** [review]

**Comment by aiwilliams** [comment]
> it may be best to remove `intestManagementGroups` and just ingest them when `ingestActiveDirectory` is set to `true`.

I think we should just ingest them when `ingestActiveDirectory: true`, but I'm curious to hear the reason you thought it something a user may not want to ingest.

**Comment by aiwilliams** [comment]
Hmm, after further reflection and consideration of the code which references `@azure/arm-managementgroups` etc. (Resource Manager), I'm wondering if the management groups are dependent on ingesting AD at all. Why not just always ingest management groups?

**Comment by kenanwarren** [comment]
I think we should ingest them irrespective of AD. If I recall you can "bucket" subscriptions into management groups and I can see that being pretty useful to writing queries that might be specific to one of those subscription buckets.

image

**Comment by ndowmon** [comment]
>Hmm, after further reflection and consideration of the code which references @azure/arm-managementgroups etc. (Resource Manager), I'm wondering if the management groups are dependent on ingesting AD at all. Why not just always ingest management groups?

@aiwilliams and @kenanwarren my sentiment is that management groups should be ingested just _once_ for each directory. If we ingested management groups for every subscription, and a user ingested two or more subscriptions in the same directory, all of the management groups would be duplicated in J1.

**Comment by ndowmon** [comment]
Actually, we should probably ingest management groups when **Configure Subscription Instances** is checked.

Screen Shot 2021-05-24 at 8 44 17 AM

**Comment by aiwilliams** [comment]
> we should probably ingest management groups when **Configure Subscription Instances** is checked

That sounds great, thanks @ndowmon !

**Review by kenanwarren — DISMISSED** [review]

**Review by kenanwarren — APPROVED** [review]

**Pull request merged**
